### ISSUE TITLE
Encoding Input

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework1G4#24]
Hi @ubsuny/hw1g4_cp23-1 

 We are trying to figure out division operation, so at first we should encode input to quantam states. I can see you performed multiplication operation using qiskit. Please let us know how you start encoding your input. For example if I have to encode number 4 to quantam state, how can I perform this.

**Comment by poojashresthacode** [comment]
So we started by implementing different gates in the input qubits. First we thought hadamard and XOR in combination would work but it didn't. We did trial and error method to perform multiplication. 
I think first of all you should play with qubits so as to get the division algorithm.

**Comment by poojashresthacode** [comment]
@yasmensarhan27 Am I right? Please enlighten more.

**Comment by pratibha77118** [comment]
@poojashresthacode thanks for explaining what you have done to implement your multiplication operation in qiskit and would like to know how you assign your classical numbers to quantam state at your first step. @yasmensarhan27 I would appreciate if you could share your understanding on this.

**Comment by WildJimmy** [comment]
Hi all,

I worked on multiplication and had to sort this issue out, so hopefully my implementation could help. 

The general idea is to use your qubits to represent your input parameters in binary. For a simple example, if I wanted to do 2 x 1, I would need 4 qubits since 2 is a 2-bit number in binary ("11"), 1 is a 1-bit number, and we need our numbers to each be stored in the same number of bits (at least for multiplication, but it's probably similar for division). 

So we make the quantum register in our circuit size 8 bits (2 for the first number, 2 for the second, and 4 for the output state). The first 2 qubits must represent the number 2 in binary, so I then need to flip each of my "on" qubits into the |1> state by the command `circuit.x(q[0])`
`circuit.x(q[1])`
Which will flip them from |0> to |1>, repeating for 1, we want the next two qubits to read "01", so
`circuit.x(q[3])`
We skip 2 since we want it to stay at 0. This will give us our first 4 qubits in the states
|1>|1>, |0>|1>
Which represents 2, then 1 in binary.

From here your algorithm will likely be much different for division, but hopefully this can help!

**Comment by pratibha77118** [comment]
@WildJimmy Thanks for making this clear. I however cannot figure out the way to develop quantum circuit for division function. Is it possible to implement like multiplication by considering a number and multiplying it with a number in inverse?

**Comment by yasmensarhan27** [comment]
Hi @pratibha77118  can you check my algorithm part on the main repository and let me know if you understand the Idea
I made it simple between 0 and 1
